config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :users, only: [:show]
 
  resources :posts do
    resources :comments
  end
  resources :recipes
  resources :comments, only: [:create, :destroy]
  


  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :ingredients, :instructions, :cook_time, presence: true
    validates :name, uniqueness: true
    belongs_to :user
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!
    def index
        @recipes = Recipe.all.order("created_at DESC")
    end

    def new
       @recipe = Recipe.new
    end
 
    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.user_id = current_user.id
        if @recipe.valid?
            @recipe.save
            redirect_to recipe_path(@recipe)
        else
            flash[:errors] = @recipe.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        @recipe = Recipe.find_by(id: params[:id])
    end
       
    def edit
        @recipe = Recipe.find(params[:id])
    end
   
    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update_attributes(recipe_params)
            redirect_to recipes_path(@recipe)
            flash[:notice] = 'recipe was updated.'
        else
            render :edit
        end
    end

    def destroy
        @recipe = Recipe.find(params[:id])
        @recipe.destroy
        redirect_to recipes_path(@recipe)
    end

    private
    def recipe_params
        params.require(:recipe).permit(:ingredients, :name, :instructions, :cook_time, :user_id)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<h1>New Recipe:</h1>

<%= form_for(@recipe) do |r| %>

    <%= r.label :name %>
    <%= r.text_field :name %>
    <%= r.hidden_field :user_id %>

    <%= r.label :ingredients %>
    <%= r.text_area :ingredients %>

    <%= r.label :instructions %>
    <%= r.text_area :instructions %>

    <%= r.label :cook_time %>
    <%= r.text_field :cook_time %>

    <%= r.submit "Submit" %>

<% end %>

app/views/recipes/edit.html.erb
<h2>Edit Recipe : </h2>

<%= render "form" %>

<%= form_tag(recipe_path(@recipe), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/recipes/index.html.erb
<h2>Welcome <%= current_user.name %></h2>
<h3>Here's a list of all recipes: </h3><br />
  <% @recipes.each do |recipe| %>
    <ul>
      <p>
        <li><%= link_to recipe.name, recipe_path(recipe.id) %>
      </p>
    </ul>
  <% end %>

app/views/recipes/new.html.erb
<h2>Create New Recipe: </h2>

<%= render "form" %>

app/views/recipes/show.html.erb
<h1>Welcome <%= current_user.name %></h1>
<h2>Your newly created recipe: </h2>

<% if current_user %>
    <strong><%= link_to "Edit Recipe", edit_recipe_path(@recipe.id) %></strong>
    <br><br>
<% end %>



<strong>Name: </strong><%= @recipe.name %> | By: <%= link_to @recipe.user.name, user_path(@recipe.user) %><br /><br />
<strong>Ingredients: </strong><%= @recipe.ingredients %><br />
<strong>Instructions: </strong><%= @recipe.instructions %><br />
<strong>Cook Time: </strong><%= @recipe.cook_time %><br />