config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :users, only: [:show]
 
  resources :posts do
    resources :comments
  end
  resources :recipes
  resources :comments, only: [:create, :destroy]
  


  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    has_many :comments
    has_many :users, through: :comments
    validates :title, :content, presence: true
    validates :title, uniqueness: true
    validates :content, length: { maximum: 500}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    #GET /posts
    def index
        @posts = Post.all.order("created_at DESC")
    end

     #GET /posts/new
    def new
        @post = Post.new
        @comment = Comment.new(post_id: params[:post_id])
    end
    
   #POST /posts/new
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.valid?
            @post.save
            redirect_to post_path(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :new
        end
    end

     #GET /posts/id
     def show
        @user = User.find_by(id: params[:id])
        @post = Post.find_by(id: params[:id])
        @comment = Comment.new
        @comment.post_id = @post.id
            #redirect_to post_path
     end

    #GET /posts/id/edit
    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
            redirect_to action: :index
            flash[:notice] = 'post was updated.'
        else
            render 'edit'
        end
    end    
   

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path(@post)
    end


    private
    def post_params
        params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div>

<h4>Comment by <%= comment.user_name %></h4>
<p class="comment"><%= comment.content %></p>
</div>

<p>Posted <%= distance_of_time_in_words(comment.post.created_at, comment.created_at) %> later</p>

app/views/posts/_form.html.erb
<h1>Welcome <%= current_user.name%></h1>
<% if !!flash[:errors] %>
<ul>
<%= flash[:errors].each do |error| %>
    <li><%= error %></li>
<% end %>
</ul>
<% end %>

<%= form_for(@post) do |f| %>
    <%= f.label :title %>
    <%= f.hidden_field :user_id %>
    <%= f.text_field :title %>
    
    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.submit "Submit" %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit post : </h2>

<%= render 'form' %>

<%= form_tag(post_path(@post), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/posts/index.html.erb
<h2>Welcome <%= current_user.name %>.</h2>
<h3>Here is a list of all posts: </h3>
  <% @posts.each do |p| %>
    <div class="post">
        <ul>
          <p>
            <li><%= link_to p.title, post_path(p.id) %></li> | By: <%= link_to p.user.name, user_path(p.user.id) %>
          </p>
        </ul>
    </div>
  <% end %>

app/views/posts/new.html.erb
<h2>Create New Post: </h2>
<%= render "form" %>

app/views/posts/show.html.erb
<h2>Welcome <%= current_user.name %></h2>

<% if @post.user_id %>
    <strong><%= link_to "Edit Post", edit_post_path(@post.id) %></strong> 
    <br><br>
<% end %>

<strong>Title: </strong><%= @post.title %><br><br> | By: <%= link_to @post.user.name, user_path(@user) %><br /><br />

<strong>Content: </strong><%= @post.content %>

<h3>Comments(<%= @post.comments.size %>)</h3>
<div>

<% @post.comments.each do |comment| %>
    <% comment_user = User.find_by(id: comment.user_name) %>
    <strong>Comment by: </strong><%= link_to comment_user, user_path(comment_user.id) %>
    <p class="comment"><%= comment.content %>
    <p>Posted <%= distance_of_time_in_words(comment.post.created_at, comment.created_at) %> ago</p>
<% end %>

</div>




<section class="comment">
<h3>Leave a comment:</h3>
<%= render partial: 'comments/form' %>
<br>
</section>







   