config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :users, only: [:show]
 
  resources :posts do
    resources :comments
  end
  resources :recipes
  resources :comments, only: [:create, :destroy]
  


  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
 
#before_action :configure_permitted_parameters, if: :devise_controller?
  def home
    #@user = User.find_or_create_by(params[:id])
  end
    
  

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:name, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:login, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update,
        keys: [:name, :email, :password_confirmation, :current_password])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>My Wellness Community</title>
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="css/styles.css" rel="stylesheet" />

</head>

<body id="page-top">
<!-- About-->
        <section class="about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <p class="text-white-50">
                          <strong>My Wellness Community</strong> is a place for people who are focused on living a healthy lifestyle. We can connect with one another and share recipes and post some of our ideas. The wellness community is a growing community consisted of like minded individuals whose focus is to do better for their bodies and the planet. 
                        </p>
                        <p>
                          My Wellness Community App is a Rails web application created by Daniel Carvalho as a portfolio project in association with Flatiron School's Online Software Engineering Program. Used Ruby on Rails to build the application and used the Gem Bootstrap to style it. 
                        </p>
                    </div>
                </div>
            </div>
        </section>

    <% if @posts && !@posts.empty? %>
      <h3>Here's a list of all your posts:</h3>
      <% @posts.each do |post| %>
        <%= link_to post.title, post_path(post) %>
      <% end %> 
    <% end %>

    <% if @recipes && @recipes.empty? %>
      <h3>Here's a list of all your recipes:</h3>
      <% @recipes.each do |r| %>
        <%= link_to r.name, recipe_path(r) %>
      <% end %> 
    <% end %>

  </div>

</body>
</html>