config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  resources :users, only: [:show]
 
  resources :posts do
    resources :comments
  end
  resources :recipes
  resources :comments, only: [:create, :destroy]
  


  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}
  devise_scope :user do 
      get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do 
    get 'logout', to: 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>My Wellness Community</title>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />

  </head>

  <body id="page-top">
  


    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
      <% if type == "notice" %>
        <div class="bg-green-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
    <% end %>

  <!-- Navigation-->
  <% if user_signed_in? %> 
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", root_path %></li>
          <li><%= link_to "Home", user_path(current_user.id) %></li>
          <li><%= link_to "All Posts", posts_path(@post) %></li>
          <li><%= link_to "All Recipes", recipes_path(@recipe) %></li>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "New Recipe", new_recipe_path %></li>
          <li><%= link_to "Log out", logout_path %></li>
        </ul>
      </div>
    </div>

  <% else %>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Login", login_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %></li>
          <li><%= link_to "Sign Up", signup_path, class:"btn btn-default block" %></li>
        </ul>
      </div>
  </nav>
  <% end %>
</nav>

<!-- Masthead-->
<header class="masthead">
    <div class="container d-flex h-100 align-items-center">
        <div class="mx-auto text-center">
            <h1 class="mx-auto my-0 text-uppercase">My Wellness Community</h1>
            <h2 class="text-white-50 mx-auto mt-2 mb-5">A community of like minded individuals focused on being good to themselves and the planet by living a healthy lifestyle.</h2>
        </div>
    </div>
</header>



  <section class="section">
    <div class="content">
    <%= image_tag("Wellness.jpg", :alt => "wellness feed") %>
        <div class="content has-text-centered">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>

      <%= yield %>

    </div>
  </section>

  <footer class="footer bg-black small text-center text-white-50"><div class="container"><strong>My Wellness Community</strong> by <a href="https://www.linkedin.com/in/daniel-carvalho-98a40859/">Daniel Carvalho</a> &copy; 2020</div></footer>
  
  <!-- Bootstrap core JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
  <!-- Third party plugin JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <!-- Core theme JS-->
  <script src="js/scripts.js"></script>
</body>
  
</html>